
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuyTicket
{

using System;
    using System.Collections.Generic;
    
public partial class Film
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Film()
    {

        this.Seans = new HashSet<Sean>();

    }


    public int Id { get; set; }

    public string Film_Name { get; set; }

    public int Year { get; set; }

    public int Duration { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sean> Seans { get; set; }

}

}
