
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuyTicket
{

using System;
    using System.Collections.Generic;
    
public partial class Sean
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sean()
    {

        this.Tickets = new HashSet<Ticket>();

    }


    public int Id { get; set; }

    public System.DateTime Seans_Data { get; set; }

    public System.TimeSpan Seans_Time { get; set; }

    public int Price { get; set; } 

    public int Film_Id { get; set; }

    public int Type_Id { get; set; }

    public int Hall_Id { get; set; }



    public virtual Film Film { get; set; }

    public virtual Hall Hall { get; set; }

    public virtual Type Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ticket> Tickets { get; set; }

}

}
