
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuyTicket
{
     
using System;
    using System.Collections.Generic;
    
public partial class Ticket
{

    public int Id { get; set; }

    public string Email { get; set; }

    public int Seat_Row { get; set; }

    public int Seat_Col { get; set; }

    public System.DateTime Ticket_DateTime { get; set; }

    public int Seans_Id { get; set; }



    public virtual Sean Sean { get; set; }

}

}
